server:
  port: 8008
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka 
spring:
  application:
    name: ws-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
            - GET
            - POST
            allowedHeaders: '*'
      discovery:
        locator:
          enabled: true
      routes:
      - id: chat-service
        uri: lb://CHAT-SERVICE
        predicates:
        - Path=/chat-service/**
        filters:
        - AddResponseHeader=Access-Control-Allow-Origin, *
        #- DedupeResponseHeader=Access-Control-Allow-Origin
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*'
