server:
  port: 8008
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka 
spring:
  application:
    name: ws-gateway
  cloud:
    gateway:
      routes:
      - id: chat-service
        uri: lb://chat-service
        predicates:
        - Path=/chat-service/**
        filters:
        - RewritePath=/chat-service/(?.*), /${remains}
