server:
  port: 8008
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka 
spring:
  application:
    name: ws-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: chat-service
        uri: lb://CHAT-SERVICE
        predicates:
        - Path=/chat-service/**
        #filters:
        #- RewritePath=/chat-service/**, /${remains}
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*'
