server:
  port: 8002
spring:
  application:
    name: gateway-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8001/eureka
  instance:
    hostname: localhost
zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
#  ignoredServices: '*'
  routes:
    resource-service:
      path: /resource/**
      service-id: resource-service
      strip-prefix: true
    user-service:
      path: /user/**
      service-id: user-service
      strip-prefix: true
    config-service:
      path: /config/**
      service-id: config-service
      strip-prefix: true
